spice_mix = set()
print(f"Initial spice mix id : {id(spice_mix)}")
print(f"Initial spice mix id : {spice_mix}")
spice_mix.add("curry")
spice_mix.add("pepper")
print(f"After  spice mix id : {id(spice_mix)}")
print(f"After  spice mix id : {spice_mix}")
